# Generated by Django 4.2.6 on 2023-10-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('kroy_no', models.IntegerField(verbose_name='')),
                ('ras_tkani', models.IntegerField(verbose_name='')),
                ('ras_dublerin', models.IntegerField(verbose_name='')),
                ('edinitsa', models.IntegerField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Крой',
            },
        ),
        migrations.CreateModel(
            name='Kroy_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pachka', models.CharField(max_length=200, verbose_name='')),
                ('razmer', models.CharField(max_length=200, verbose_name='')),
                ('rost', models.CharField(max_length=200, verbose_name='')),
                ('stuk', models.IntegerField(verbose_name='')),
                ('kroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kroy', verbose_name='')),
            ],
            options={
                'verbose_name': 'Крой',
            },
        ),
    ]
