# Generated by Django 4.2.6 on 2023-10-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroy',
            name='edinitsa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Единица'),
        ),
        migrations.AlterField(
            model_name='kroy',
            name='kroy_no',
            field=models.IntegerField(verbose_name='Крой номер'),
        ),
        migrations.AlterField(
            model_name='kroy',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='kroy',
            name='ras_dublerin',
            field=models.FloatField(verbose_name='Расход дублерин'),
        ),
        migrations.AlterField(
            model_name='kroy',
            name='ras_tkani',
            field=models.FloatField(verbose_name='Расход ткани'),
        ),
    ]
