# Generated by Django 4.2.6 on 2023-10-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_kroy_edinitsa_alter_kroy_kroy_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroy_detail',
            name='kroy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kroy', verbose_name='Крой'),
        ),
        migrations.AlterField(
            model_name='kroy_detail',
            name='pachka',
            field=models.CharField(max_length=200, verbose_name='Пачка'),
        ),
        migrations.AlterField(
            model_name='kroy_detail',
            name='razmer',
            field=models.CharField(max_length=200, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='kroy_detail',
            name='rost',
            field=models.CharField(max_length=200, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='kroy_detail',
            name='stuk',
            field=models.IntegerField(verbose_name='Штук'),
        ),
    ]
