# Generated by Django 4.2.6 on 2023-10-21 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_kroy_detail_kroy_alter_kroy_detail_pachka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kroy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kroy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Примечение'),
        ),
        migrations.AlterField(
            model_name='kroy',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование'),
        ),
    ]
